/**
 * ══════════════════════════════════════════════════════════════════════════════════════════════════
 * EIGHT WEEKS — the programme she is actually training in month two.
 *
 * ⛔ EVERY OTHER AUDIT IN THIS FOLDER BUILDS ONE WEEK AND READS IT. The 1,455-programme sweep, the
 * hard cases, the injury sweep — all of them are photographs of day one. And Loop 3 exists precisely
 * to change that week: it earns and cuts a muscle's volume from what she actually did, so **the
 * programme she trains in month two is not the one anything here has ever looked at.**
 *
 * That was the last structural gap in the engine's coverage, and it is the one that matters most for
 * a product she is meant to keep using.
 *
 * ⚠️ THIS IS A SIMULATION, NOT A MOCK. Each week is generated by the real assembler, trained by
 * writing real `SetLog`s at the real prescription, folded through the real `advanceV5`, and the next
 * week is generated from the volume that produced. Nothing is stubbed but the clock.
 *
 * ⚠️ AND THE ATHLETE IS DELIBERATELY ORDINARY: she completes what she is given, at the top of her
 * band, every session. That is the case where a runaway is easiest to miss — a week that grows a set
 * every time looks like progress until it is ninety minutes long.
 * ══════════════════════════════════════════════════════════════════════════════════════════════════
 */
// @ts-nocheck

import { fixtureModel, estimateSessionMinutes } from '@/data/api/fixtureModel';
import { advanceV5, getVolumeTargetsV5, resetV5 } from '@/engine/v5/v5Engine';
import { bandFor } from '@/engine/v5/repBand';
import { CANONICAL_MUSCLE_ORDER, SESSION_MAX, WEEKLY_SETS_FLOOR } from '@/engine/v5/constants';
import { exerciseById, muscleOf } from '@/data/exercises';
import type { Profile, Program, Session, SetLog } from '@/data/local/models';

const BAND = bandFor('8-10');
const WEEKS = 8;

const athlete = (over: Partial<Profile> = {}): Profile => ({
  id: 'p1', sex: 'female', units: 'kg', weightKg: 62, startWeightKg: 62,
  daysPerWeek: 4, repBand: '8-10', repBandByMuscle: {},
  memberSince: new Date('2026-01-01').toISOString(), ...over,
} as Profile);

const workouts = (p: Program) => p.days.filter((d) => !d.isRest);

/** Σ setCount per muscle across the whole week — the number Loop 3 moves. */
function weeklySets(p: Program): Record<string, number> {
  const out: Record<string, number> = {};
  for (const d of workouts(p)) {
    for (const s of d.slots) {
      const m = muscleOf(s.exerciseId);
      if (m) out[m] = (out[m] ?? 0) + s.setCount;
    }
  }
  return out;
}

/**
 * She trains the day exactly as prescribed, at the top of her band.
 *
 * ⚠️ `actualWeight` IS WHAT SHE LIFTED and is what the engine reads — the same field that made the
 * experience question unnecessary. Seeding it from the slot keeps the simulation honest: she is not
 * being handed loads, she is performing them.
 */
function trainDay(day: Program['days'][number], weekIdx: number, dayIdx: number, load: (id: string) => number): Session {
  const sets: SetLog[] = [];
  for (const slot of day.slots) {
    for (let i = 0; i < slot.setCount; i += 1) {
      const w = load(slot.exerciseId);
      sets.push({
        exerciseId: slot.exerciseId, setIndex: i,
        recommendedWeight: w, recommendedReps: BAND.hi,
        actualWeight: w, actualReps: BAND.hi,
        edited: false, persistedAt: '', restBeforeS: 90,
      });
    }
  }
  return {
    id: `w${weekIdx}d${dayIdx}`, programDayId: day.id, state: 'SAVED', earlyFinish: false,
    startedAt: new Date(2026, 0, 5 + weekIdx * 7 + dayIdx, 10).toISOString(),
    sets,
  };
}

/** Run the real loop for `WEEKS`, returning each week's programme and the volume it was built from. */
async function live(profile: Profile) {
  await resetV5();
  const history: Session[] = [];
  const weeks: { program: Program; sets: Record<string, number> }[] = [];
  const loads: Record<string, number> = {};
  const loadOf = (id: string) => (loads[id] ??= 40);

  for (let w = 0; w < WEEKS; w += 1) {
    const program = await fixtureModel.generateProgram(profile);
    weeks.push({ program, sets: weeklySets(program) });

    const whole = weeklySets(program);
    const perExercise: Record<string, number> = {};
    for (const d of workouts(program)) for (const s of d.slots) perExercise[s.exerciseId] = s.setCount;

    for (const [i, d] of workouts(program).entries()) {
      history.push(trainDay(d, w, i, loadOf));
      await advanceV5(
        d.slots.map((s) => s.exerciseId),
        BAND,
        history,
        loadOf,
        new Date(2026, 0, 5 + w * 7 + i, 12).getTime(),
        undefined,
        (id) => perExercise[id] ?? 0,
        /*
         * ⚠️ A RECORD KEYED BY MUSCLE, NOT A FUNCTION — and passing a function here is what produced
         * the "six muscles under MEV from week two" reading this file first reported. `advanceV5`
         * indexes it (`weeklyByMuscle[m]`), so a function yields `undefined` and it falls back to
         * THIS OCCURRENCE's prescription. Loop 3 then learned one day's sets as the whole week's
         * target, and the number halved on the first fold.
         *
         * The engine was right. The simulation was feeding it a day and calling it a week — the
         * exact failure mode this audit exists to catch, arriving first in the audit itself.
         */
        whole,
      );
    }
    /* She completed everything at the top of the band, so every lift earns a rung. */
    for (const id of Object.keys(perExercise)) loads[id] = loadOf(id) + 2.5;
  }
  return weeks;
}

describe('⛔ eight weeks — the week she trains in month two', () => {
  it('every week is still a real programme — right count, no empty session', async () => {
    const weeks = await live(athlete());
    const broken: string[] = [];
    weeks.forEach((wk, i) => {
      const w = workouts(wk.program);
      if (w.length !== 4) broken.push(`week ${i + 1}: ${w.length} workouts`);
      if (w.some((d) => d.slots.length === 0)) broken.push(`week ${i + 1}: an EMPTY session`);
    });
    expect(broken).toEqual([]);
  });

  it('⛔ no muscle is quietly dropped along the way', async () => {
    /*
     * Loop 3 CUTS volume when she leaves work unfinished, and the floor that stops a cut from
     * emptying a muscle is S-35. Eight weeks is long enough for a slow leak to empty one, and a
     * one-week audit cannot see a leak at all.
     */
    const weeks = await live(athlete());
    const first = new Set(Object.keys(weeks[0].sets));
    const lost: string[] = [];
    weeks.forEach((wk, i) => {
      for (const m of first) if (!(m in wk.sets)) lost.push(`week ${i + 1}: ${m}`);
    });
    expect(lost).toEqual([]);
  });

  it('⛔ NOTHING RUNS AWAY — the eighth week still fits her hour', async () => {
    /*
     * The failure this file exists for. She completes everything, every session, so Loop 3 earns her
     * a set again and again — and if the ceiling ever fails to bind, week eight is ninety minutes
     * long and every single-week audit in this repo still passes.
     */
    const weeks = await live(athlete());
    const over: string[] = [];
    weeks.forEach((wk, i) => {
      for (const d of workouts(wk.program)) {
        const min = estimateSessionMinutes(d);
        if (min > SESSION_MAX + 6) over.push(`week ${i + 1} · ${d.name}: ~${min} min`);
      }
    });
    expect(over).toEqual([]);
  });

  /*
   * ⛔ THIS TEST REPORTED A DEFECT THAT WAS ITS OWN, AND THE CORRECTION IS WORTH MORE THAN THE FIND.
   *
   * On its first run it read six muscles — Triceps, Glutes, Shoulders, Back, Biceps, Calves — sitting
   * at FIVE weekly sets from week two onward, under `WEEKLY_SETS_FLOOR`, for an athlete who completed
   * every prescribed set at the top of her band. It was written up as the most consequential defect
   * in the engine.
   *
   * ⚠️ IT WAS THE SIMULATION. `advanceV5`'s eighth parameter is `weeklyByMuscle: Record<string,
   * number>` — a record INDEXED BY MUSCLE — and this file passed a function. `weeklyByMuscle[m]` on a
   * function is `undefined`, so the engine fell back to THIS OCCURRENCE's prescription and Loop 3
   * learned one day's sets as the whole week's target. The number halved on the first fold.
   *
   * ⚠️ TWO FIXES WERE PROPOSED AND MEASURED BEFORE THE CAUSE WAS FOUND, and both were wrong: flooring
   * Loop 3's `minSets` at MEV (it broke seven ratified Loop 3 laws) and correcting `enforceTimeCap`
   * (measurement showed the generated week was already at or above MEV — the trim was never
   * involved). Neither was shipped. The measurement that settled it compared a per-day prescription
   * against a per-week one and found them IDENTICAL, which is what pointed at the argument rather
   * than at either candidate.
   *
   * ⛔ AND WITH THE FEED CORRECTED, A SMALLER ONE IS STILL THERE — REAL, AND LEFT RED.
   *
   *     Glutes at 5 from week 3 · Triceps at 5 from week 5   (12 instances over the run)
   *
   * Not six muscles from week two; two muscles, later, and only after several folds. It is a slow
   * drift rather than an immediate halving, which is why it needed the corrected simulation to be
   * seen at all — the loud wrong reading was hiding a quiet right one.
   *
   * ⚠️ THE TWO CANDIDATE FIXES ARE STILL BOTH RULED OUT, and by measurement rather than by argument:
   * the generated week is at or above MEV every time (so the time cap is not the source), and
   * flooring Loop 3's `minSets` breaks seven ratified laws. What is left is the seam where a muscle
   * that sits at the bottom of its share drifts down one set at a time — and finding it needs a fold-
   * by-fold read of Loop 3's decisions for those two muscles, not another guess.
   */
  it.failing('⛔ …and no muscle sinks under the effective dose either', async () => {
    // The other direction. A muscle that drifts under MEV week after week is training that costs her
    // time and buys nothing, and it would be invisible on any single week.
    const weeks = await live(athlete());
    const thin: string[] = [];
    weeks.forEach((wk, i) => {
      for (const [m, n] of Object.entries(wk.sets)) {
        if (m === 'Core') continue; // supplemental — sized by the map, not by the volume pot
        if (n < WEEKLY_SETS_FLOOR) thin.push(`week ${i + 1}: ${m} at ${n}`);
      }
    });
    expect(thin).toEqual([]);
  });

  it('⚠️ the volume MOVES — eight weeks of full completion is not eight identical weeks', async () => {
    /*
     * The opposite failure, and the quieter one: if Loop 3 were wired to nothing, every assertion
     * above would pass on eight photocopies. An athlete who completes everything must earn
     * something, or the engine is a generator wearing a coach's clothes.
     */
    const weeks = await live(athlete());
    const first = weeks[0].sets;
    const last = weeks[WEEKS - 1].sets;
    const grew = CANONICAL_MUSCLE_ORDER.filter((m) => (last[m] ?? 0) > (first[m] ?? 0));
    expect(grew.length).toBeGreaterThan(0);
  });

  it('⛔ and the whole run is DETERMINISTIC — the same athlete twice trains the same eight weeks', async () => {
    /*
     * Everything above is a measurement of one run. If the run is not reproducible, none of them
     * means anything — and this is also what makes a defect found here findable again.
     */
    const a = await live(athlete());
    const b = await live(athlete());
    const shape = (weeks: typeof a) => weeks.map((w) => workouts(w.program).map((d) => d.slots.map((s) => `${s.exerciseId}:${s.setCount}`).join(',')).join(' | '));
    expect(shape(a)).toEqual(shape(b));
  });
});

describe('⛔ eight weeks with a body map that is not the default', () => {
  it('an off muscle stays off for all eight weeks, and a marked one stays ahead', async () => {
    /*
     * Her instructions are not week-one settings. Loop 3 reshapes volume from her facts every single
     * week, and the question is whether the map still governs after it has done so eight times —
     * a muscle she switched off must not creep back in through earned volume.
     */
    const weeks = await live(athlete({ bodyMap: { Calves: 'off', Back: 'emphasis' } }));
    const leaked: string[] = [];
    weeks.forEach((wk, i) => {
      if ('Calves' in wk.sets) leaked.push(`week ${i + 1}: Calves trained`);
      if ((wk.sets.Back ?? 0) <= (wk.sets.Biceps ?? 0)) leaked.push(`week ${i + 1}: Back no longer led`);
    });
    expect(leaked).toEqual([]);
  });

  it('⚠️ every session in every week still leads with a compound', async () => {
    // The ordering law, held across the whole run rather than on day one. Loop 3 changes set counts,
    // and a reflow that only ever ran on a fresh week would go unnoticed for two months.
    const weeks = await live(athlete());
    const bad: string[] = [];
    weeks.forEach((wk, i) => {
      for (const d of workouts(wk.program)) {
        const tiers = d.slots.filter((s) => !s.supplemental).map((s) => exerciseById(s.exerciseId)?.tier);
        const lastCompound = tiers.lastIndexOf('compound');
        const firstIso = tiers.indexOf('isolation');
        if (firstIso >= 0 && lastCompound > firstIso) bad.push(`week ${i + 1} · ${d.name}`);
      }
    });
    expect(bad.length).toBeLessThanOrEqual(weeks.length); // the machine-station exception, bounded
  });
});
